apiVersion: v1
kind: Secret
metadata:
  name: acs-secret
  labels:
    app: active-cluster-service
type: Opaque
stringData:
  # Hosts del replicaSet de MongoDB (reemplazar por valores reales)
  MONGO_HOST_01: "mongo-01.example.com:27017"
  MONGO_HOST_02: "mongo-02.example.com:27017"
  MONGO_HOST_03: "mongo-03.example.com:27017"
  MONGO_URI_SHARED: "mongodb://user:pass@mongo-01.example.com:27017,mongo-02.example.com:27017,mongo-03.example.com:27017/acs?replicaSet=rs0&readPreference=secondaryPreferred"
  MONGO_URI_CACHE: "mongodb://user:pass@mongo-01.example.com:27017,mongo-02.example.com:27017,mongo-03.example.com:27017/acs_cache?replicaSet=rs0&readPreference=secondaryPreferred"
