spring.data.mongodb.uri=${MONGO_URI_SHARED:mongodb://localhost:27017/acs}
acs.cache.mongodb-uri=${MONGO_URI_CACHE:mongodb://localhost:27017/acs_cache}
acs.default-environment=dev
cache.ttl-seconds=${CACHE_TTL_SECONDS:30}
logging.level.root=INFO
logging.level.ar.com.paas.active.cluster.service=DEBUG
