# Produccion: alta disponibilidad con replicaSet
spring.data.mongodb.uri=${MONGO_URI_SHARED}
acs.cache.mongodb-uri=${MONGO_URI_CACHE}
acs.default-environment=prd
cache.ttl-seconds=${CACHE_TTL_SECONDS:30}
logging.level.root=WARN
logging.level.ar.com.paas.active.cluster.service=WARN
