spring.data.mongodb.uri=${MONGO_URI_SHARED}
acs.cache.mongodb-uri=${MONGO_URI_CACHE}
acs.default-environment=qas
cache.ttl-seconds=${CACHE_TTL_SECONDS:30}
logging.level.root=INFO
logging.level.ar.com.paas.active.cluster.service=INFO
