# Perfil PRD
spring.data.mongodb.uri=${MONGO_URI_SHARED}
csm-cache.mongodb.uri=${MONGO_URI_CACHE}
csm.scheduler.enabled=${CSM_SCHEDULER_ENABLED:true}
csm.scheduler.fixed-delay=${CSM_SCHEDULER_FIXED_DELAY:30000}
csm.probe.timeout-ms=${CSM_PROBE_TIMEOUT_MS:3000}
csm.probe.max-retries=${CSM_PROBE_MAX_RETRIES:2}
csm.manual-grace-seconds=${CSM_MANUAL_GRACE_SECONDS:300}
logging.level.ar.com.paas.cluster.status.monitor=WARN
management.tracing.sampling.probability=0.1
