# Perfil DEV
spring.data.mongodb.uri=${MONGO_URI_SHARED:mongodb://localhost:27017/paas_shared_dev}
csm-cache.mongodb.uri=${MONGO_URI_CACHE:mongodb://localhost:27017/paas_cache_dev}
csm.scheduler.enabled=true
csm.scheduler.fixed-delay=15000
csm.probe.timeout-ms=3000
logging.level.ar.com.paas.cluster.status.monitor=DEBUG
