# Perfil QAS
spring.data.mongodb.uri=${MONGO_URI_SHARED}
csm-cache.mongodb.uri=${MONGO_URI_CACHE}
csm.scheduler.enabled=true
csm.scheduler.fixed-delay=30000
csm.probe.timeout-ms=3000
logging.level.ar.com.paas.cluster.status.monitor=INFO
