spring:
  application:
    name: cluster-status-service
  data:
    mongodb:
      uri: ${MONGODB_URI:mongodb://localhost:27017/multi-clusters}

cluster:
  data-center: default
  active: true
  polling-interval-seconds: 30
